version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: mentesnotaveis
    container_name: mentesnotaveis-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - mentesnotaveis

  db:
    image: mysql:5.7
    container_name: mentesnotaveis-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - mentesnotaveis

  nginx:
    image: nginx:alpine
    container_name: mentesnotaveis-nginx
    restart: unless-stopped
    ports:
      - 8005:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - mentesnotaveis

networks:
  mentesnotaveis:
    driver: bridge
